version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
before_build:
- cmd: nuget restore serilog-sinks-eventgrid.sln
build:
  project: serilog-sinks-eventgrid.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/sirkirby/api/v2/package
  api_key:
    secure: +FYD4lCyVQxiL9+UPw3bpo2bc7osbMy7tIahYeCoZN4+XgaBIFakxiI4vnjOZUFR
  skip_symbols: true
  on:
    branch: master
    Configuration: Release
- provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version) release
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: 7jJt8R5qmdaczjCT8wSlaiosdwhKmn7tSsBYUAvgHHpRPuwE0jx9rnrvdQuUSTLv
  artifact: /.*\.nupkg/
  force_update: true
  on:
    branch: master
    Configuration: Release